### ISSUE TITLE
What is the latest version of Postgres supported by GitHub Actions?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-postgresql#122]
At present we have a disparate set of repos that use different versions of Postgres. 
I'd like to just specify "latest" in our `ci.yml` file and always use the most up-to-date version. 💭

**Comment by nelsonic** [comment]
```yml
    services:
      postgres:
        image: postgres:latest
```
Is what you need. ✅ 

More advanced/native usage: https://dev.to/lxxxvi/github-action-using-pre-installed-postgres-5144
